### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by RajGM**
Footer section completed as per figma design, color is changing according to theme as well.

### CODE REVIEW

**Review by Tess99854 — CHANGES_REQUESTED** [review]
The Footer component is only present in the Home page  `index.tsx` fille, can you move it there please instead of the  `_app.tsx` file

**Comment by RajGM** [comment]
> 

Oh, I missed that point.
Doing it now.
Thanks for pointing it out @Tess99854 

But aren't navbar and footer are supposed to be present on every page?

**Comment by RajGM** [comment]
Done @Tess99854

**Comment by Tess99854** [comment]
> > 
> 
> Oh, I missed that point. Doing it now. Thanks for pointing it out @Tess99854
> 
> But aren't navbar and footer are supposed to be present on every page?

It  depends on the use case, but I thought it wouldn't be necessary to have the contact information etc displayed on the dashboard page and creation form page.
However, in case we wanted to add it to all pages it should be added to the layout component just like the navbar since that component wraps our whole application.

**Comment by RajGM** [comment]
> > > 
> > 
> > 
> > Oh, I missed that point. Doing it now. Thanks for pointing it out @Tess99854
> > But aren't navbar and footer are supposed to be present on every page?
> 
> It depends on the use case, but I thought it wouldn't be necessary to have the contact information etc displayed on the dashboard page and creation form page. However, in case we wanted to add it to all pages it should be added to the layout component just like the navbar since that component wraps our whole application.



> > > 
> > 
> > 
> > Oh, I missed that point. Doing it now. Thanks for pointing it out @Tess99854
> > But aren't navbar and footer are supposed to be present on every page?
> 
> It depends on the use case, but I thought it wouldn't be necessary to have the contact information etc displayed on the dashboard page and creation form page. However, in case we wanted to add it to all pages it should be added to the layout component just like the navbar since that component wraps our whole application.

Should we discuss it with the team, or make it appear in only homepage, or make it appear in all page?

**Comment by Tess99854** [comment]
Let's make it appear on the homepage only for now and discuss it with the team in the next meeting

**Comment by RajGM** [comment]
> Let's make it appear on the homepage only for now and discuss it with the team in the next meeting

Okay.
It's in the index file.

**Comment by abdelhakeem** [comment]
I think the colors are reversed for light and dark themes, also the background color should be `#201B48` for the dark theme and `#2F2E41` for the light theme, and the logo should be white for both:

Peek 2022-06-20 12-39

Also, there is too much space between the logo and the "Hydra Wallet" text:

image

Other than that, I think everything looks good!

EDIT: to make the logo color white, just give it a `className` of `brightness-0 invert`.

**Comment by RajGM** [comment]
> I think the colors are reversed for light and dark themes, also the background color should be `#201B48` for the dark theme and `#2F2E41` for the light theme, and the logo should be white for both:
> 
> Peek 2022-06-20 12-39
> 
> Also, there is too much space between the logo and the "Hydra Wallet" text:
> 
> image
> 
> Other than that, I think everything looks good!
> 
> EDIT: to make the logo color white, just give it a `className` of `brightness-0 invert`.

Ok, will improve it.

**Comment by Tess99854** [comment]
@RajGM can you rebase and solve the conflicts please?

**Comment by RajGM** [comment]
> @RajGM can you rebase and solve the conflicts please?

Yes, I will do it by today @Tess99854

**Comment by Tess99854** [comment]
The png logo that you replaced is also used for the navbar, and now it doesn't work correctly, can you please return it and add a separate png for the footer, we can also get rid of it (in the footer) because it doesn't match the background

**Comment by RajGM** [comment]
> The png logo that you replaced is also used for the navbar, and now it doesn't work correctly, can you please return it and add a separate png for the footer, we can also get rid of it (in the footer) because it doesn't match the background

Hi @Tess99854 
I am creating a new branch with the mentioned improvements, as manually solving the merge conflict is taking a lot of time.

**Pull request closed without merging**
