### PR TITLE
Fetch members onchain

### PR DESCRIPTION
**Pull request by haianhltr**
Work on showing members, and updating shares.

### CODE REVIEW

**Comment by haianhltr** [comment]
I'm just creating this pull request to work on while waiting for @abdelhakeem and @apratim branch to be merged.

**Comment by abdelhakeem** [comment]
Can you explain more what this is about?

**Comment by haianhltr** [comment]
> Can you explain more what this is about?

I'm currently working on getting all the members in the hydra wallet, total inflow, current balance, etc. Basically, just for tweaking around.

**Comment by abdelhakeem** [comment]
Cool, but there is an open PR about the balance thing. So it's best to be specific about what this should be about.

**Pull request closed without merging**
