### PR TITLE
Create wallet UI

### LINKED ISSUE #8: Work on the form (create a wallet) without including the functionalities

### PR DESCRIPTION
**Pull request by Tess99854**

### CODE REVIEW

**Comment by abdelhakeem** [comment]
Great work!

You removed the navbar padding or that was by mistake?

Screen Shot 2022-06-15 at 15 54 42

Also, I think we need some margin at the top of the header here and above:

Screen Shot 2022-06-15 at 15 54 58

**Comment by Tess99854** [comment]
@abdelhakeem I removed the x-axis padding since we already have an x margin (that helped fix the alignment) but surely we need a margin around the header, I will fix that

**Comment by abdelhakeem** [comment]
> @abdelhakeem I removed the x-axis padding since we already have an x margin (that helped fix the alignment) but surely we need a margin around the header, I will fix that

The problem is that the x-margin is auto, so on mobile screens when the navbar becomes full width there is no margin and the logo is on the edge:

Logo Margin

Maybe having a `p-6 sm:px-0` would fix that? Was the problem that the navbar is not aligned with the content?

**Comment by abdelhakeem** [comment]
Thanks! I think we can get that merged now.

**Pull request merged**
