### PR TITLE
Added Home hero section

### LINKED ISSUE #1: Add the Hero Section
## Description

- Add the `Hero Section of Landing Page`

ref: https://www.figma.com/file/slALV1iSxF9Si68f0VpGxs/HydraSuggestion?node-id=0%3A1

### PR DESCRIPTION
**Pull request by NikhilSharma03**
## Description  

- This PR resolves #1 
- Added Home hero section

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
Discord Webhook Test: Added Hero Section

**Comment by abdelhakeem** [comment]
Excellent progress!

Need to make it responsive like the Figma design for the mobile version. How it's done in Tailwind CSS is by having your mobile styles as the default ones and then extending them with styles for larger screens using Tailwind's [responsive design utility classes](https://tailwindcss.com/docs/responsive-design).

For instance, this will display the `div` in full width on mobile screens and in half width on `sm` screens and _above_:

```html
<div className="w-full sm:w-1/2">
  .
  .
  .
</div>
```

Also, I think the image in the hero section shouldn't be in a `div` next to the text, but rather somehow behind it. Not sure, but this could be done with CSS Grid (check Tailwind's grid utility classes).

Make sure to resolve the conflicts (rebase on `frontend_client`).

**Comment by NikhilSharma03** [comment]
Understood @abdelhakeem. I'll make these changes.

**Comment by NikhilSharma03** [comment]
# After Changes

- Added responsiveness
- The image now will be behind the text (using `absolute` positioning)

#### Mobile
Screenshot 2022-06-16 205804

#### Tablet
Screenshot 2022-06-16 205829

// @abdelhakeem

**Comment by abdelhakeem** [comment]
@NikhilSharma03 Neat stuff! Let's merge this after resolving the conflicts.

**Review by abdelhakeem — APPROVED** [review]

**Comment by NikhilSharma03** [comment]
@abdelhakeem I'm not seeing any conflicts.

Screenshot 2022-06-16 223327

**Comment by abdelhakeem** [comment]
> @abdelhakeem I'm not seeing any conflicts.
> 
> Screenshot 2022-06-16 223327

My bad, I had the last menu item chosen here. Ok, I'm merging this...
image

**Comment by NikhilSharma03** [comment]
Thank you 🙌

**Pull request merged**
