### PR TITLE
Carousel+Correct Styling 

### PR DESCRIPTION
**Pull request by anshuman-dev**

### CODE REVIEW

**Comment by anshuman-dev** [comment]
Resolves [#7 ](https://github.com/NikhilSharma03/hydra-keys/issues/7)

**Comment by anshuman-dev** [comment]
@abdelhakeem . I hope this can be merged now?

**Comment by abdelhakeem** [comment]
> @abdelhakeem . I hope this can be merged now?

Yeah, sure! I think we are just missing the mobile version (like in the Figma design), which is a lot simpler. On small screens the carousel would be hidden.

**Comment by Tess99854** [comment]
@anshuman-dev I also think it should be centered and the two disabled models (for example wallet and token models in the design) should be there at all times.
The disabled state is described by the gray color, once a user clicks on next the previous model will be on top with a white background and black logo, this is also why I think you need to use a div and a logo instead of images for every circle.
If you have any questions about how the meaning of the design don't hesitate to ask me

**Comment by anshuman-dev** [comment]
> @anshuman-dev I also think it should be centered and the two disabled models (for example wallet and token models in the design) should be there at all times. The disabled state is described by the gray color, once a user clicks on next the previous model will be on top with a white background and black logo, this is also why I think you need to use a div and a logo instead of images for every circle. If you have any questions about how the meaning of the design don't hesitate to ask me

@Tess99854 Does it match requirements now?

**Review by Tess99854 — COMMENTED** [review]
@anshuman-dev This looks amazing, is there a way to prevent moving to the next point automatically without having to press the pause button, I think it's enough for us to have next and previous buttons (sorry for being overly demanding xD )

**Comment by anshuman-dev** [comment]
> @anshuman-dev This looks amazing, is there a way to prevent moving to the next point automatically without having to press the pause button, I think it's enough for us to have next and previous buttons (sorry for being overly demanding xD )

Sure. Done!

**Review by NikhilSharma03 — APPROVED** [review]
LGTM!
I think we can remove this button now.
Screenshot 2022-06-27 203841

**Comment by anshuman-dev** [comment]
> LGTM! I think we can remove this button now. Screenshot 2022-06-27 203841

Removed. Thanks!

**Pull request merged**
