### PR TITLE
Add cluster picker

### LINKED ISSUE #53: Add cluster chooser to UI
- Add a cluster chooser to the UI to choose between `devnet` and `mainnet` (`mainnet-beta`)
- Update the global cluster state in the Redux store

### PR DESCRIPTION
**Pull request by abdelhakeem**
Resolves #53

### CODE REVIEW

**Comment by Tess99854** [comment]
@abdelhakeem I think it would be better if we use a select input to show the users which cluster is selected without them having to click on the button,  usually when a dropdown is used It infers that an action is about to happen when they click on a submenu so in our case it might be a bit confusing

**Comment by abdelhakeem** [comment]
@Tess99854 Thanks for your review! I'll update the cluster chooser in the navbar to use a select input instead.

What about the buttons in the drawer menu on mobile screens? I think they're okay as they behave more like radio buttons.

**Comment by Tess99854** [comment]
@abdelhakeem yes the mobile version is perfect 👍 , and so is the select input now, do you think we should store the cluster value in the store so we can use it in different components?

**Comment by abdelhakeem** [comment]
> @abdelhakeem yes the mobile version is perfect +1 , and so is the select input now, do you think we should store the cluster value in the store so we can use it in different components?

Yes, it is currently stored in the store in [`walletSlice`](https://github.com/NikhilSharma03/hydra-keys/blob/a479cdb28e2b12c19ea122f41e9f58e3c6503ccb/redux/features/wallet/walletSlice.ts) and can be accessed as follows:

https://github.com/NikhilSharma03/hydra-keys/blob/a479cdb28e2b12c19ea122f41e9f58e3c6503ccb/components/ClusterPickerItem.tsx#L23

**Comment by Tess99854** [comment]
@abdelhakeem great! after fixing the conflicts we can merge this

**Pull request merged**
