### PR TITLE
Add balance field

### PR DESCRIPTION
**Pull request by anshuman-dev**

### CODE REVIEW

**Comment by abdelhakeem** [comment]
I think it would be very tricky to keep the balance in the database in sync with that on the blockchain, so an easier approach would be to just fetch it from the blockchain. 

EDIT: One way to do this is to get the balance of the native account via `getAccountInfo`.

**Comment by abdelhakeem** [comment]
You can use something like this to get the balance from the blockchain:

```typescript
const fanout = await Fanout.fromAccountAddress(
  connection,
  new PublicKey(wallet.pubkey)
)

const nativeAccountPubkey = fanout.accountKey
const nativeAccountInfo = await connection.getAccountInfo(
  nativeAccountPubkey
)

setBalance(nativeAccountInfo?.lamports ?? 0)
```

**Comment by anshuman-dev** [comment]
> ```ts
> const fanout = await Fanout.fromAccountAddress(
>   connection,
>   new PublicKey(wallet.pubkey)
> )
> 
> const nativeAccountPubkey = fanout.accountKey
> const nativeAccountInfo = await connection.getAccountInfo(
>   nativeAccountPubkey
> )
> 
> setBalance(nativeAccountInfo?.lamports ?? 0)
> ```

Yup, I have been doing the following, (was trying directly from blockchain for Native address)
```
async () => {
        const fanout = await Fanout.fromAccountAddress(
          connection,
          new PublicKey(hydraWallet.pubkey)
        )
        setNativeAccount(fanout.accountKey.toBase58())
      }

      const nativpbkey = new PublicKey(nativeAccount);
      const SOL = connection.getAccountInfo(nativpbkey)
      let balance = await connection.getBalance(nativpbkey);
      setSOLBalance(balance / LAMPORTS_PER_SOL)
```
But the create button is not responding, idk where i went wrong

**Comment by abdelhakeem** [comment]
It'd be nice if we also display:
- The total inflow of the Hydra wallet, this is available in the `Fanout` object as `totalInflow`
- The total available shares of the Hydra wallet, this is available in the `Fanout` object as `totalAvailableShares`

**Comment by anshuman-dev** [comment]
> It'd be nice if we also display:
> 
> * The total inflow of the Hydra wallet, this is available in the `Fanout` object as `totalInflow`
> * The total available shares of the Hydra wallet, this is available in the `Fanout` object as `totalAvailableShares`

This is covered by https://github.com/NikhilSharma03/hydra-keys/pull/106

**Comment by anshuman-dev** [comment]
@abdelhakeem , should we merge this one then?

**Comment by abdelhakeem** [comment]
> @abdelhakeem , should we merge this one then?

Yup, works perfectly! Later on we might address the fact that we have to refresh the page for the balance to update.

**Comment by anshuman-dev** [comment]
> > @abdelhakeem , should we merge this one then?
> 
> Yup, works perfectly! Later on we might address the fact that we have to refresh the page for the balance to update.

Yes. Just observed this.

**Pull request merged**
