### PR TITLE
Add "Manage" page functionality

### LINKED ISSUE #39: Manage wallets page: get all the hydra wallets related to the connected member and display them

### PR DESCRIPTION
**Pull request by abdelhakeem**
Resolves #39 

I suggest we all use [SWR](https://swr.vercel.app) for data fetching for consistency and because it helps with state and cache management.

### CODE REVIEW

**Comment by Tess99854** [comment]
@abdelhakeem looks great! I think the user shouldn't be able to see "manage" in the navbar if his wallet is not connected. 
It would also be nice if we use something like a spinner when the data is loading 😛 , check this: https://tailwindcss.com/docs/animation

Here's the spinner SVG : 

```
<svg
  class="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  viewBox="0 0 24 24"
>
  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
  <path
    class="opacity-75"
    fill="currentColor"
    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
  ></path>
</svg>
```

**Comment by abdelhakeem** [comment]
> @abdelhakeem looks great! I think the user shouldn't be able to see "manage" in the navbar if his wallet is not connected. It would also be nice if we use something like a spinner when the data is loading stuck_out_tongue , check this: https://tailwindcss.com/docs/animation
> 
> Here's the spinner SVG :
> 
> ```
> <svg
>   class="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
>   xmlns="http://www.w3.org/2000/svg"
>   fill="none"
>   viewBox="0 0 24 24"
> >
>   <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
>   <path
>     class="opacity-75"
>     fill="currentColor"
>     d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
>   ></path>
> </svg>
> ```

Thanks for your review! Yeah, I think also "Create" shouldn't be there unless the user is connected, I'll update the navbar in this PR to reflect this. Will also add the spinner.

**Comment by Tess99854** [comment]
@abdelhakeem in that case will the "Get started" button prompt the user to connect his wallet? 
we also need to implement protected routes so the user can't access the `/manage` and `/create` routes even when he types the URL manually
These can be added as separate issues

**Comment by Tess99854** [comment]
One more detail that I think @alexandredelaitre can help with, do we need to add query params to our API calls that specify which cluster we're on, for example when we query the hydra wallets of the user we can use something like:

```
/api/wallets/user/${publickey}?cluster='devnet'
```

**Comment by abdelhakeem** [comment]
@Tess99854 Yes, "Keep Exploring" would take them down the page and "Get Started" would prompt them to connect their wallet if it's not connected, shall it redirect them to the "Create" page in case they're connected?

And yes, I think we need to add the following tasks:
- Implement hero section button functionality
- Add protected routes for `/create` and `/manage`

> do we need to add query params to our API calls that specify which cluster we're on

Good point, yes, we do need that.

**Comment by wezn** [comment]
> 



> One more detail that I think @alexandredelaitre can help with, do we need to add query params to our API calls that specify which cluster we're on, for example when we query the hydra wallets of the user we can use something like:
> 
> ```
> /api/wallets/user/${publickey}?cluster='devnet'
> ```

At the moment query params won't work but I agree it would be really useful to have them, will quickly add this! Thanks for pointing this out!!

**Comment by abdelhakeem** [comment]
Current status:
- ~Waiting for cluster chooser to be ready~
- ~Waiting for cluster param in API endpoint to be available~

**Comment by abdelhakeem** [comment]
This now fetches wallets within the currently chosen cluster.

**Comment by Tess99854** [comment]
@abdelhakeem i believe we can merge this now

**Review by Tess99854 — APPROVED** [review]

**Pull request merged**
