### PR TITLE
Sec-3 Text Carousel

### LINKED ISSUE #7: work on the third section of the landing page

### PR DESCRIPTION
**Pull request by anshuman-dev**

### CODE REVIEW

**Comment by anshuman-dev** [comment]
@abdelhakeem Can you reason out what checks this pr is failing?

**Comment by abdelhakeem** [comment]
> @abdelhakeem Can you reason out what checks this pr is failing?

I think @NikhilSharma03 can help with that as he has access to the [deployment logs](https://vercel.com/nikhilsharma03/hydra-keys/5KRw65BBSFKVgshqFNM4V3JCwNxD) on Vercel.

**Comment by anshuman-dev** [comment]
> > @abdelhakeem Can you reason out what checks this pr is failing?
> 
> I think @NikhilSharma03 can help with that as he has access to the [deployment logs](https://vercel.com/nikhilsharma03/hydra-keys/5KRw65BBSFKVgshqFNM4V3JCwNxD) on Vercel.

Ohk! @NikhilSharma03 What checks do we have for the Vercel deployment?

**Comment by NikhilSharma03** [comment]
@anshuman-dev 
Screenshot 2022-06-16 231729

**Comment by NikhilSharma03** [comment]
Run `npm run build` to check these issues on your env.

**Comment by anshuman-dev** [comment]
> Run `npm run build` to check these issues on your env.

That's the weird stuff actually as I can see the deployment on my end but am using yarn. I will try with npm

**Comment by anshuman-dev** [comment]
Closing this PR. Complimented by : [#46 ](https://github.com/NikhilSharma03/hydra-keys/pull/46)

**Pull request closed without merging**
