### PR TITLE
opacity of background image in less than 960px

### PR DESCRIPTION
**Pull request by rishabh-vasudevan**
Making the background image a little bigger and reducing the opacity to match the one given in the figma file.

### CODE REVIEW

**Comment by Tess99854** [comment]
@rishabh-vasudevan thanks for fixing that, can you also make the font smaller for the mobile version? we can merge this afterward

**Comment by rishabh-vasudevan** [comment]
> @rishabh-vasudevan thanks for fixing that, can you also make the font smaller for the mobile version? we can merge this afterward 

Yes, surely

**Comment by Tess99854** [comment]
@rishabh-vasudevan is this PR ready to be merged ?

**Comment by rishabh-vasudevan** [comment]
> @rishabh-vasudevan is this PR ready to be merged ?

I think it should be good now.

**Pull request merged**
