### PR TITLE
Api add spl endpoint

### LINKED ISSUE #74: Add an SPL token AFTER creating a hydrawallet

### PR DESCRIPTION
**Pull request by Tess99854**

### CODE REVIEW

**Comment by abdelhakeem** [comment]
Amazing work! I think you're just missing the part where we revert the database changes (remove SPL token and set `acceptSPL` to `false`) when the transaction fails or when transaction confirmation fails, you can see an example [here](https://github.com/NikhilSharma03/hydra-keys/blob/85b63a9966decbb1830c24cf8acd9b58e95cbcec/pages/api/createHydraWallet/index.ts#L78-L87).

Also, something we wanna ask about is whether we should allow setting an SPL token multiple times or disallow it as done here, and what effect it has.

**Comment by Tess99854** [comment]
@abdelhakeem About the second point, two options are possible : 
* the SPL token can only be set once (which is how everything works now) 
* the SPL token can be overridden by setting it more than once: in this case, we'll need to update the API and the frontend to allow the edit option when the wallet already has an SPL token.

**Comment by abdelhakeem** [comment]
> @abdelhakeem About the second point, two options are possible :
> 
>     * the SPL token can only be set once (which is how everything works now)
> 
>     * the SPL token can be overridden by setting it more than once: in this case, we'll need to update the API and the frontend to allow the edit option when the wallet already has an SPL token.

Let's keep it as it is now then until we know how the Hydra program would behave if we override the current SPL token.

**Comment by abdelhakeem** [comment]
Are there any pending changes or is this ready now for merging?

**Pull request merged**
